theme: jekyll-theme-slate
title: "Boa Cred - Relatório de Dados"
show_downloads: true
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
